kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-traffic-to-hellow-world
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: hello-world-depl
  ingress:
  - {}
  policyTypes:
  - Ingress